name: Revz1
favicon: null
layout_spectrum: 0.6562508700881153
typography_spectrum: 0.4142007583286613
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2034662466030568
  lightness: 0.5102605479769409
  saturation: 0.9339108867570758
  rhythmicContrast: 0.3380020500626415
purpose: []
